# Generated by Django 6.0.5 on 2026-06-07 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buysell_app', '0002_area_district_state_delete_location_area_district_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Area',
        ),
    ]
