# Generated by Django 6.0.5 on 2026-06-08 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buysell_app', '0005_cardetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='subCategory',
            new_name='subcategory',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='Category',
            new_name='category',
        ),
    ]
