# Generated by Django 6.0.5 on 2026-06-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysell_app', '0007_bikedetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardetails',
            name='model',
            field=models.CharField(default='Unkown', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='fuel',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('CNG & Hybrids', 'CNG & Hybrids'), ('Electric', 'Electric'), ('LPG', 'LPG')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='owners',
            field=models.CharField(choices=[('1', '1st Owner'), ('2', '2nd Owner'), ('3', '3rd Owner'), ('4', '4th Owner'), ('4+', '4+ Owners')], max_length=10),
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='transmission',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], max_length=50),
        ),
    ]
