# Generated by Django 6.0.5 on 2026-06-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysell_app', '0008_cardetails_model_alter_cardetails_fuel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetails',
            name='owners',
            field=models.CharField(choices=[('1', '1st Owner'), ('2', '2nd Owner'), ('3', '3rd Owner'), ('4', '4th Owner'), ('4+', '4+ Owners')], default='1', max_length=10),
        ),
    ]
