# Generated by Django 6.0.2 on 2026-06-18 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buysell_app', '0011_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BikeDetails',
        ),
    ]
