# Generated by Django 6.0.2 on 2026-06-19 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysell_app', '0012_delete_bikedetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotorcycleDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('fuel', models.CharField(choices=[('Petrol', 'Petrol'), ('Electric', 'Electric'), ('Diesel', 'Diesel')], max_length=20)),
                ('km_driven', models.PositiveIntegerField()),
                ('owner', models.CharField(choices=[('1', '1st Owner'), ('2', '2nd Owner'), ('3', '3rd Owner'), ('4', '4th Owner'), ('5', '4+ Owner')], max_length=10)),
                ('engine_cc', models.PositiveIntegerField()),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='buysell_app.product')),
            ],
        ),
    ]
