# Generated by Django 6.0.2 on 2026-06-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysell_app', '0013_motorcycledetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorcycledetails',
            name='insurance_type',
            field=models.CharField(choices=[('Valid', 'Valid'), ('No Insurance', 'No Insurance')], default='No Insurance', max_length=50),
        ),
    ]
