# Generated by Django 6.0.2 on 2026-06-23 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysell_app', '0015_scooterdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='BicycleDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('bicycle_type', models.CharField(max_length=50)),
                ('gear_type', models.CharField(max_length=50)),
                ('owner', models.CharField(choices=[('1', '1st Owner'), ('2', '2nd Owner'), ('3', '3rd Owner'), ('4', '4th Owner'), ('5', '4+ Owner')], max_length=10)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='buysell_app.product')),
            ],
        ),
    ]
