# Generated by Django 6.0.5 on 2026-06-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysell_app', '0016_bicycledetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bicycledetails',
            name='bicycle_type',
        ),
        migrations.AlterField(
            model_name='bicycledetails',
            name='gear_type',
            field=models.CharField(choices=[('Gear', 'Gear Cycle'), ('Non Gear', 'Non Gear Cycle')], max_length=20),
        ),
    ]
