# Generated by Django 6.0.5 on 2026-06-24 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysell_app', '0017_remove_bicycledetails_bicycle_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseApartmentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('Sale', 'Sale'), ('Rent', 'Rent')], max_length=20)),
                ('property_type', models.CharField(choices=[('Flats / Apartments', 'Flats / Apartments'), ('Independent / Builder Floors', 'Independent / Builder Floors'), ('Farm House', 'Farm House'), ('House & Villa', 'House & Villa'), ('Duplex', 'Duplex')], max_length=100)),
                ('bhk', models.CharField(choices=[('1', '1 BHK'), ('2', '2 BHK'), ('3', '3 BHK'), ('4', '4 BHK'), ('5', '4+ BHK')], max_length=10)),
                ('bathrooms', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '4+')], max_length=10)),
                ('furnishing', models.CharField(choices=[('Furnished', 'Furnished'), ('Semi-Furnished', 'Semi-Furnished'), ('Unfurnished', 'Unfurnished')], max_length=30)),
                ('listed_by', models.CharField(choices=[('Builder', 'Builder'), ('Dealer', 'Dealer'), ('Owner', 'Owner')], max_length=20)),
                ('super_builtup_area', models.PositiveIntegerField(help_text='Includes walls and common areas.')),
                ('carpet_area', models.PositiveIntegerField(help_text='Actual usable area inside the property.')),
                ('maintenance', models.PositiveIntegerField(blank=True, null=True)),
                ('total_floors', models.PositiveIntegerField()),
                ('floor_no', models.PositiveIntegerField()),
                ('car_parking', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '3+')], max_length=10)),
                ('facing', models.CharField(choices=[('North', 'North'), ('South', 'South'), ('East', 'East'), ('West', 'West'), ('North-East', 'North-East'), ('North-West', 'North-West'), ('South-East', 'South-East'), ('South-West', 'South-West')], max_length=20)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='buysell_app.product')),
            ],
        ),
    ]
