# Generated by Django 6.0.5 on 2026-06-30 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysell_app', '0021_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('Apple', 'Apple'), ('Samsung', 'Samsung'), ('Xiaomi', 'Xiaomi'), ('Redmi', 'Redmi'), ('POCO', 'POCO'), ('Realme', 'Realme'), ('OnePlus', 'OnePlus'), ('Vivo', 'Vivo'), ('OPPO', 'OPPO'), ('iQOO', 'iQOO'), ('Nothing', 'Nothing'), ('Motorola', 'Motorola'), ('Google Pixel', 'Google Pixel'), ('Nokia', 'Nokia'), ('Honor', 'Honor'), ('Huawei', 'Huawei'), ('Infinix', 'Infinix'), ('Tecno', 'Tecno'), ('Lava', 'Lava'), ('Micromax', 'Micromax'), ('Lenovo', 'Lenovo'), ('Asus', 'Asus'), ('Sony', 'Sony'), ('LG', 'LG'), ('HTC', 'HTC'), ('BlackBerry', 'BlackBerry'), ('JioPhone', 'JioPhone'), ('Other', 'Other')], max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='buysell_app.product')),
            ],
        ),
    ]
