# Generated by Django 6.0.5 on 2026-06-30 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysell_app', '0022_mobiledetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaptopDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('Apple', 'Apple'), ('Dell', 'Dell'), ('HP', 'HP'), ('Lenovo', 'Lenovo'), ('Asus', 'Asus'), ('Acer', 'Acer'), ('MSI', 'MSI'), ('Samsung', 'Samsung'), ('LG', 'LG'), ('Microsoft', 'Microsoft'), ('Huawei', 'Huawei'), ('Honor', 'Honor'), ('Razer', 'Razer'), ('Alienware', 'Alienware'), ('Gigabyte', 'Gigabyte'), ('Avita', 'Avita'), ('Infinix', 'Infinix'), ('Realme', 'Realme'), ('Chuwi', 'Chuwi'), ('Others', 'Others')], max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='buysell_app.product')),
            ],
        ),
    ]
